#!/usr/bin/env bash

set -eu

repo_uri="https://x-access-token:${DEPLOY_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
remote_name="origin"
main_branch="master"
target_branch="gh-pages"

cd "$GITHUB_WORKSPACE"

git config user.name "$GITHUB_ACTOR"
git config user.email "${GITHUB_ACTOR}@bots.github.com"

#git checkout "$target_branch"
#git rebase "${remote_name}/${main_branch}"

python stapnm.py jalstlm
cd jalstlm
git init
git config user.name "$GITHUB_ACTOR"
git config user.email "${GITHUB_ACTOR}@bots.github.com"

git add --all
git commit -am'स्थाप॑नम्'
if [ $? -ne 0 ]; then
    echo "nothing to commit"
    exit 0
fi

git branch -m "$target_branch"

git remote add  "$remote_name" "$repo_uri" -t "$target_branch" # includes access token
git push --force --set-upstream "$remote_name" "$target_branch"